USE Mobills;
DROP TABLE IF EXISTS dbo.Receitas;
DROP TABLE IF EXISTS dbo.Despesas;

CREATE TABLE Receitas
(
	[Id] INT NOT NULL IDENTITY(1, 1),
	[Descricao] VARCHAR(255),
	[Valor] DECIMAL(7, 2) NOT NULL DEFAULT(0.00),
	[Data] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Recebido] BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_Receitas PRIMARY KEY (Id),
);

CREATE TABLE Despesas
(
	[Id] INT NOT NULL IDENTITY(1, 1),
	[Descricao] VARCHAR(255),
	[Valor] DECIMAL(7, 2) NOT NULL DEFAULT(0.00),
	[Data] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Pago] BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_Despesas PRIMARY KEY (Id),
);